# Generated by Django 3.0.7 on 2020-06-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'PrayerRequests',
            },
        ),
    ]
