# Generated by Django 3.0.7 on 2020-06-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibaapp', '0002_prayerrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('hub_image', models.ImageField(default='hub_default.jpg', upload_to='hub_images')),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hub',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.AlterModelOptions(
            name='prayerrequests',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'PrayerRequests'},
        ),
        migrations.AlterModelOptions(
            name='sermons',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'Sermons'},
        ),
    ]
