# Generated by Django 3.0.7 on 2020-07-01 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibaapp', '0003_auto_20200630_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Album',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.AlterField(
            model_name='hub',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='AlbumImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mibaapp.Album')),
            ],
            options={
                'verbose_name_plural': 'AlbumImages',
                'ordering': ['-date_posted'],
            },
        ),
    ]
