# Generated by Django 3.0.7 on 2020-07-01 16:15

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mibaapp', '0004_auto_20200701_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
        migrations.AddField(
            model_name='hub',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='albumimages',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[1000, 550], upload_to='gallery_images'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='hub_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[1000, 550], upload_to='hub_images'),
        ),
    ]
