# Generated by Django 3.0.7 on 2020-07-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibaapp', '0006_auto_20200701_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
