# Generated by Django 3.0.7 on 2020-07-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibaapp', '0008_auto_20200701_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
