# Generated by Django 3.0.7 on 2020-07-08 10:04

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mibaapp', '0011_sermons_sermon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('song_image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='sermon_default.jpg', force_format=None, keep_meta=True, quality=100, size=[1000, 550], upload_to='songs_images')),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Songs',
                'ordering': ['-date_posted'],
            },
        ),
    ]
