# Generated by Django 3.0.7 on 2020-07-08 17:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mibaapp', '0012_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='hub_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='hub_default.jpg', force_format=None, keep_meta=True, quality=100, size=[1000, 550], upload_to='hub_images'),
        ),
    ]
