# Generated by Django 3.0.7 on 2020-07-28 13:24

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mibaapp', '0014_auto_20200708_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='article_pdfs')),
                ('article_image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='article_default.jpg', force_format=None, keep_meta=True, quality=100, size=[1000, 550], upload_to='article_images')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.DeleteModel(
            name='PrayerRequests',
        ),
    ]
