# Generated by Django 3.0.7 on 2020-08-05 12:36

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mibaapp', '0015_auto_20200728_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsCorner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('kids_image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='hub_default.jpg', force_format=None, keep_meta=True, quality=100, size=[1000, 550], upload_to='hub_images')),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'KidsCorner',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.DeleteModel(
            name='Hub',
        ),
    ]
